# Generated by Django 4.0.5 on 2022-07-02 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='data_registrazione',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
