# Generated by Django 4.0.5 on 2022-07-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0004_alter_anagrafica_abi_alter_anagrafica_cab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='email',
            field=models.EmailField(default='mail_di_prova@gmail.it', max_length=50),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='pec',
            field=models.EmailField(default='mail_di_prova@pec.it', max_length=50),
        ),
    ]
