# Generated by Django 4.0.5 on 2022-07-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0006_alter_anagrafica_cap_alter_anagrafica_cap2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='cap',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='cap2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='p_iva',
            field=models.CharField(max_length=50),
        ),
    ]
