# Generated by Django 4.0.5 on 2022-07-03 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0007_alter_anagrafica_cap_alter_anagrafica_cap2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='cap',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d\\d\\d\\d\\d')]),
        ),
    ]
