# Generated by Django 4.0.5 on 2022-07-03 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0015_alter_anagrafica_data_registrazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='cap',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d*5$')]),
        ),
    ]
