# Generated by Django 4.0.5 on 2022-07-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0017_alter_anagrafica_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='cap',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='p_iva',
            field=models.CharField(max_length=11),
        ),
    ]
